### ISSUE TITLE
file content not showing due to error

### ISSUE THREAD

**Issue by whuhn** [danielscherzer/GLSL#109]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 0.11.162

### Description
It doesn't display the selected file's content and says: 

An error occurred while initializing the frame's content
System.ArgumentException: No EditorOptionDefinition export found for the given option name: EditingState/EditingStateEndingMargin
Parameter name: optionId
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptionsFactoryService.GetOptionDefinitionOrThrow(String optionId)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.GetOptionValue[T](String optionId)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.GetOptionValue[T](EditorOptionKey`1 key)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_SetSite(Object pUnkSite, Boolean isCodeWindow)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.SetSite()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.InitializeView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.CreateView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.CreateAndAddView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.SetSite(Object pUnkSite)
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)

the error code is 0x80070057

### Steps to recreate
1. installed extension
2. ran visual studio 
3. open source file (.cpp, .frag, .vert etc.)
4. error occurs

### Current behavior
I can't see the file's contents

### Expected behavior
display shader source with syntax highlighting and other source files without error

**Comment by danielscherzer** [comment]
probably related to issue #117
