### ISSUE TITLE
Errors after installing the extension.

### ISSUE THREAD

**Issue by CreeperArcade** [danielscherzer/GLSL#112]
### Installed product versions
- Visual Studio: 2022 Community 17.3.5
- GLSL language integration (for VS2022): 0.11.164

### Description
Getting an error when opening a visual studio solution. Cannot see any code that I've written.

### Steps to recreate
1. Download setup file
2. Install extension
3. Wait for it to finish
4. Open any solution
5. Error pops up

![image](https://user-images.githubusercontent.com/111135852/227733963-787764c4-017f-40ae-a75d-a991d6cc6998.png)

Then, instead of the code, a window containing this pops up:
![image](https://user-images.githubusercontent.com/111135852/227734405-449e11eb-b879-4fce-b652-5ecf8c36ca4d.png)

An error occurred while initializing the frame's content
System.ArgumentException: No EditorOptionDefinition export found for the given option name: EditingState/EditingStateEndingMargin
Parameter name: optionId
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptionsFactoryService.GetOptionDefinitionOrThrow(String optionId)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.GetOptionValue[T](String optionId)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.GetOptionValue[T](EditorOptionKey`1 key)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_SetSite(Object pUnkSite, Boolean isCodeWindow)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.SetSite()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.InitializeView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.CreateView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.CreateAndAddView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.SetSite(Object pUnkSite)
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)

Disabling the extension reverts everything to normal.

Tried uninstalling it and reinstalling it but did not change anything.

**Comment by danielscherzer** [comment]
Thanks for your feedback! I'm aware that many installations of Visual Studio 2022 have problems with my extension. Microsoft is currently renovating the way extensions are written for Visual Studio. This could be connected to the issues you are having. Some of my students got my extension to work after reinstalling Visual Studio, but I for many this is not a viable solution. 

On my setup the extension is working (for now)... but not debuggable because Visual Studio throughs exceptions all over the place one time and another time everything works. This of course changes with each Visual Studio update. This is probably the fault of my extension. I probably do something not the way one should do it. But I have no clue what is the problem.

Visual Studio and extensions currently still use .Net Framework 4.8, but they want to switch to .net5/6/7/8. An external library my extension uses (OpenTK) already needs .net5, so I cannot upgrade this dependency. Even the community extension templates do not compile (in my setup)... IN my opinion, it is currently a mess developing extensions. 

So my plan is to wait till .net5 support is here and make a clean break and redo the extension from scratch.

**Comment by danielscherzer** [comment]
probably releated to issue #117

**Comment by danielscherzer** [comment]
Is this problem still an issue?
